name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Verify Chromium Installation
      run: chromium-browser --version

    - name: Run conversion script
      run: |
        chmod +x .github/scripts/generate_pdf.sh
        ./.github/scripts/generate_pdf.sh fr ./source/mohamed.md Aittaleb_Mohamed_Resume.pdf
    - name: Upload generated site
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site/

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: Aittaleb_Mohamed_Resume.pdf

    - name: Debug - List _site directory contents
      run: ls -R _site
  deploy-pages:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Download generated site
      uses: actions/download-artifact@v3
      with:
        name: site
        path: _site/

    - name: Deploy HTML and PDF to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Deploy to the gh-pages branch
        folder: _site
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Download PDF artifact
      uses: actions/download-artifact@v3
      with:
        name: output-pdf

    - name: Download HTML artifact
      uses: actions/download-artifact@v3
      with:
        name: output-html

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: |
          output_pdf.pdf
          cv.html
