name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Verify Chromium Installation
      run: chromium-browser --version

    - name: Run conversion script
      run: |
        chmod +x .github/scripts/generate_pdf.sh
        ./.github/scripts/generate_pdf.sh fr ./source/mohamed.md Aittaleb_Mohamed_Resume.pdf

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: Aittaleb_Mohamed_Resume.
        path: Aittaleb_Mohamed_Resume.pdf
